# Numpy Tutorial From the **GridU**

#### Array - Creation

In [6]:
import numpy

In [7]:
import array
# initialize arr with arr values with the signed integers
arr = array.array('i', [1,2,3,4,5])

#### The Arrange Method
Returns an array with evenly spaced elements as per the interval. The interval mentioned is half - opened i.e. [start, stop]


In [10]:
import numpy as geek

print("A\n", geek.arange(4).reshape(2,2),"\n")
print("A\n",geek.arange(4,10),"\n") # linearly
print("A\n", geek.arange(4,20,3), "\n")


A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



#### Zero Method
numpy.zeros() function returns a new array of given shape ad type, with zeros


In [11]:
b = geek.zeros(2, dtype=int)
print("Matrix b : \n", b)

a = geek.zeros([2,2], dtype=int)
print("Matrix a : \n", a)
c = geek.zeros([3,2], dtype=int)
print("Matrix c : \n", c)


## **Note** this is also similar for the "ones" geek.ones(2)

Matrix b : 
 [0 0]
Matrix a : 
 [[0 0]
 [0 0]]
Matrix c : 
 [[0 0]
 [0 0]
 [0 0]]


#### $The Linspace Method$
numpy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop]

similar to the **np.arrange**  but instead of a step

In [ ]:
print("B\n", geek.linspace(2.0,3.0, num=5, retstep=True),"\n")

# To evaluate Sin() in long range
x = geek.linspace(0,2,10)
print("A\n", geek.sin(x))

#### The Eye Method
np.eye(R,C = None, k = 0,dytpe = type<"float">) return the **diagonal value filled with one else "0"**
**K** A p+ is the upper diagonal, P- is the lower diagonal else neutral diagnoal ( main)

In [12]:
b = geek.eye(2,dtype=int)
print("Matrix b : \n", b)
a = geek.eye(4,5, k = -1)
print("Matrix a : \n", a)

Matrix b : 
 [[1 0]
 [0 1]]
Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### Creating a one - dimensional Numpy arr


In [13]:
import numpy as np

list = [100,200,300]
n = np.array(list)
print(n)

[100 200 300]


#### How to Create an empty and a Full Numpy array


In [15]:
empa = np.empty((3,4), dtype=int)
print("Empty Arr",empa)

# Create a Full Array
flla = np.full([3,3], 55, dtype=int)
print("Full Arr : ", flla)


Empty Arr [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Full Arr :  [[55 55 55]
 [55 55 55]
 [55 55 55]]


#### Manipulation of the Numpy array

In [16]:
arr = np.array([1,2,3,4,5])
v = arr.view() ## Creating view

#both arr and v have different id
print("id of arr", id(arr))
print("id of v", id(v))
# changing the original Array will effect view
arr[0] = 12

print("original arr", arr)
print("new arr", v)
# arr = np.array([1,2,3,4,5])

id of arr 4520478832
id of v 4520478544
original arr [12  2  3  4  5]
new arr [12  2  3  4  5]


#### Swap Columns of a Given Numpy Array

In [17]:
my_arr = np.arange(12).reshape(4,3)
print("original arr", my_arr)

## Swapping the column with the index of the original array
my_arr[:, [2,0]] = my_arr[:, [2,0]]

original arr [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Slack the Sequence of numpy arr horizontally

In [19]:
in_arr1 = geek.array([1,2,3])
in_arr2 = geek.array([4,5,6])

out_arr = geek.hstack((in_arr1,in_arr2))
print("horizontal stacked arr", out_arr)

## Similar to the vertical stacked array
ver_arr = geek.vstack((in_arr1,in_arr2))
print("vertical stacked arr", ver_arr)

#### Joining the array
array_new = np.concatenate((in_arr1,in_arr2),axis=0)


horizontal stacked arr [1 2 3 4 5 6]
vertical stacked arr [[1 2 3]
 [4 5 6]]


#### Combining a one and a two-dimensional Numpy Array


In [20]:
num_1d = np.arange(5)
print("one dimensional array:", num_1d)

num_2d = np.arange(10).reshape(2,5)
print("two dimensional array:", num_2d)

## Combine 1-D and 2 - D arrays and display their elements using **numpy.nditer()**

for a, b in np.nditer([num_1d,num_2d]):
    print("%d: %d" % (a, b))

one dimensional array: [0 1 2 3 4]
two dimensional array: [[0 1 2 3 4]
 [5 6 7 8 9]]
0: 0
1: 1
2: 2
3: 3
4: 4
0: 5
1: 6
2: 7
3: 8
4: 9


#### Combined Array index by index

In [21]:
gfg1 = np.array([1,2,3])
gfg2 = np.array([4,5,6])

print(np.dstack((gfg1,gfg2)))

[[[1 4]
  [2 5]
  [3 6]]]
