## 1) Import the numpy package under the name 'np' and numpy version

In [1]:
import numpy
import numpy as np
print(np.__version__)



2.4.2


## 2 Create the null vector

In [5]:
arr = np.empty([2,5], dtype=int)
print(arr)

## Memory size of the array
print("Memory size of the arr",arr.nbytes)

[[0 0 0 0 0]
 [0 0 0 0 0]]
Memory size of the arr 80


In [10]:
help(np.add)


Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [12]:
## Create a null vector of size 10 but the fifth value which is 1

arr1 = np.zeros(10, dtype=int)
print(arr1)
arr1[4] = 1
print(arr1)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [18]:
arr2 = np.linspace(10,49)
print(arr2)

arr2_reverse = np.flip(arr2)
print(arr2_reverse)

[10.         10.79591837 11.59183673 12.3877551  13.18367347 13.97959184
 14.7755102  15.57142857 16.36734694 17.16326531 17.95918367 18.75510204
 19.55102041 20.34693878 21.14285714 21.93877551 22.73469388 23.53061224
 24.32653061 25.12244898 25.91836735 26.71428571 27.51020408 28.30612245
 29.10204082 29.89795918 30.69387755 31.48979592 32.28571429 33.08163265
 33.87755102 34.67346939 35.46938776 36.26530612 37.06122449 37.85714286
 38.65306122 39.44897959 40.24489796 41.04081633 41.83673469 42.63265306
 43.42857143 44.2244898  45.02040816 45.81632653 46.6122449  47.40816327
 48.20408163 49.        ]
[49.         48.20408163 47.40816327 46.6122449  45.81632653 45.02040816
 44.2244898  43.42857143 42.63265306 41.83673469 41.04081633 40.24489796
 39.44897959 38.65306122 37.85714286 37.06122449 36.26530612 35.46938776
 34.67346939 33.87755102 33.08163265 32.28571429 31.48979592 30.69387755
 29.89795918 29.10204082 28.30612245 27.51020408 26.71428571 25.91836735
 25.12244898 24.32653061 

In [19]:
## create the 3 x 3 Matrix with the values
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
arr3 = [1,2,0,0,4,0]
print("non zeros values index",np.nonzero(arr3))

non zeros values index (array([0, 1, 4]),)


In [22]:
arr_1 = np.ones([3,3], dtype=int)
print(arr_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
random_3d_matrix = np.random.random((3,3,3))
print(random_3d_matrix)

[[[0.59378161 0.64285944 0.40619955]
  [0.483736   0.00621856 0.85326982]
  [0.64224405 0.99181389 0.26475422]]

 [[0.71590479 0.90782431 0.47999897]
  [0.10246606 0.2480493  0.48001282]
  [0.14570128 0.07408821 0.45521823]]

 [[0.63719942 0.45896877 0.39579484]
  [0.53121209 0.69436064 0.98839324]
  [0.52955638 0.056894   0.12863257]]]


### create the array with the random values and find the minimum and maximum values
arr_10 = np.random(10,10)

In [25]:
arr_10 = np.random.random((10,10))
print(arr_10)

print("maximum values of arr",arr_10.max())
print("minimum values of arr",arr_10.min())

[[0.56067963 0.68451597 0.2812607  0.49985549 0.52961384 0.87729541
  0.18855005 0.06007915 0.3602706  0.59641732]
 [0.7741881  0.5611028  0.29386951 0.4771606  0.82104244 0.9076688
  0.44478836 0.37500971 0.25860932 0.14660773]
 [0.15825366 0.49991345 0.27852502 0.45521912 0.03356959 0.64285635
  0.50105275 0.16128036 0.08693549 0.73773662]
 [0.01997414 0.10939714 0.46754542 0.16443068 0.11012795 0.82904894
  0.42905128 0.4324621  0.2788681  0.34826855]
 [0.95909577 0.37542288 0.43104483 0.59423533 0.1018192  0.83424049
  0.17027204 0.91952785 0.78803801 0.03055111]
 [0.10658156 0.11349238 0.60190809 0.39364114 0.54710602 0.08829672
  0.59503906 0.03162548 0.66649631 0.26827185]
 [0.59020544 0.18947168 0.57118923 0.73259888 0.93609969 0.40617843
  0.64789613 0.5823769  0.07779139 0.98662306]
 [0.17208641 0.34068787 0.57622676 0.86862582 0.3025049  0.90467797
  0.36088548 0.10613917 0.3737108  0.76086518]
 [0.10471279 0.84851422 0.81257822 0.45537793 0.68906238 0.15903414
  0.54024932 

In [26]:
def create_border_array_numpy(rows, cols):
    # Create an array of all ones
    arr_7 = np.ones((rows, cols), dtype=int)
    # Set the inner elements to zero using slicing (from index 1 to second-last)
    if rows > 2 and cols > 2:
        arr_7[1:-1, 1:-1] = 0
    return arr_7

# Example for a 5x5 array
array_5x5 = create_border_array_numpy(5, 5)
print(array_5x5)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [27]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False
